<?php
/**
 * General functions class
 *
 * @author ilGhera
 * @package wc-importer-for-danea-premium/includes
 *
 * @since 1.6.4
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class WCIFD_Functions
 *
 * @since 1.6.4
 */
class WCIFD_Functions {

	/**
	 * The constructor
	 *
	 * @return void
	 */
	public function __construct() {

		/* Actions */
		add_action( 'init', array( $this, 'register_attributes' ) );
		add_action( 'init', array( $this, 'products_update_request' ) );

		/* Filters */
		add_filter( 'puc_manual_check_link-wc-importer-for-danea-premium', array( $this, 'check_update_message' ) );
		add_filter( 'puc_manual_check_message-wc-importer-for-danea-premium', array( $this, 'update_message' ), 10, 2 );
	}


	/**
	 * Generate random string
	 *
	 * @param int $length the string length.
	 *
	 * @return string
	 */
	public static function rand_md5( $length ) {

		$max    = ceil( $length / 32 );
		$random = '';
		for ( $i = 0; $i < $max; $i ++ ) {
			$random .= md5( microtime( true ) . mt_rand( 10000, 90000 ) );
		}

		return substr( $random, 0, $length );
	}


	/**
	 * Define the names of the fiscal checkout form fields
	 *
	 * @param string $field the field to be defined.
	 *
	 * @return string
	 */
	public static function get_italian_tax_fields_names( $field ) {

		$cf_name      = null;
		$pi_name      = null;
		$pec_name     = null;
		$pa_code_name = null;

		/* Fields generated by the plugin */
		if ( get_option( 'wcexd_company_invoice' ) || get_option( 'wcexd_private_invoice' ) ) {

			$cf_name      = 'billing_wcexd_cf';
			$pi_name      = 'billing_wcexd_piva';
			$pec_name     = 'billing_wcexd_pec';
			$pa_code_name = 'billing_wcexd_pa_code';

		} else {

			/*Supported plugins */

			/* WooCommerce Aggiungere CF e P.IVA */
			if ( class_exists( 'WC_BrazilianCheckoutFields' ) ) {
				$cf_name = 'billing_cpf';
				$pi_name = 'billing_cnpj';

				/* WooCommerce P.IVA e Codice Fiscale per Italia */
			} elseif ( class_exists( 'WooCommerce_Piva_Cf_Invoice_Ita' ) || class_exists( 'WC_Piva_Cf_Invoice_Ita' ) ) {
				$cf_name      = 'billing_cf';
				$pi_name      = 'billing_piva';
				$pec_name     = 'billing_pec';
				$pa_code_name = 'billing_pa_code';

				/* YITH WooCommerce Checkout Manager */
			} elseif ( function_exists( 'ywccp_init' ) ) {
				$cf_name = 'billing_Codice_Fiscale';
				$pi_name = 'billing_Partita_IVA';

				/* WOO Codice Fiscale */
			} elseif ( function_exists( 'woocf_on_checkout' ) ) {
				$cf_name = 'billing_CF';
				$pi_name = 'billing_iva';
			}
		}

		switch ( $field ) {
			case 'cf_name':
				return $cf_name;
			case 'pi_name':
				return $pi_name;
			case 'pec_name':
				return $pec_name;
			case 'pa_code_name':
				return $pa_code_name;
		}
	}


	/**
	 * Get user ID by tax code
	 *
	 * @param string $tax_code the tax code.
	 *
	 * @return int
	 */
	public static function get_user_id_by_tax_code( $tax_code ) {

		global $wpdb;

		$result = $wpdb->get_results(
			$wpdb->prepare(
				"
                SELECT user_id
                FROM $wpdb->usermeta
                WHERE meta_value = %s
                ",
				$tax_code
			),
			ARRAY_A
		);

		return $result[0]['user_id'];
	}


	/**
	 * Get country code
	 *
	 * @param string $state_name the full country name.
	 *
	 * @return string
	 */
	public static function get_country_code( $state_name ) {

		$countries = WC()->countries->countries;

		foreach ( $countries as $key => $value ) {

			if ( $value === $state_name ) {

				return $key;

			} elseif ( $key === $state_name ) {

				return $state_name;

			}
		}

	}


	/**
	 * Decode the XML values
	 *
	 * @param  string $field the XML field.
	 *
	 * @return string
	 */
	public static function decode_xml_value( $field = null ) {

		$decoded = json_decode( json_encode( $field ), true );
		$output  = $decoded ? $decoded[0] : null;

		return $output;
	}


	/**
	 * Get the WC order (ID) previously imported from Danea Easyfatt
	 *
	 * @param  int $number The Danea Easyfatt order ID.
	 *
	 * @return int
	 */
	public static function get_order_by_number( $number ) {

		$orders = wc_get_orders(
			array(
				'meta_key'   => 'wcifd-order-number',
				'meta_value' => $number,
				'return'     => 'ids',
			)
		);

		return isset( $orders[0] ) ? $orders[0] : null;

	}


	/**
	 * Get the WC payment gateway used in the order imported from Danea Easyfatt
	 *
	 * @param  string $method the payment gateway coming from Danea Easyfatt.
	 *
	 * @return string
	 */
	public static function get_wc_payment_gateway( $method ) {

		switch ( $method ) {
			case 'Paypal':
			case 'Carta di credito':
				return array(
					'id'    => 'paypal',
					'title' => 'PayPal',
				);
			case 'Contrassegno':
				return array(
					'id'    => 'cod',
					'title' => 'Cash on Delivery',
				);
			case 'Bonifico bancario':
				return array(
					'id'    => 'bacs',
					'title' => 'Direct Bank Transfer',
				);
			default:
				return null;
		}

	}


	/**
	 * Delete orphan SKUs from the database
	 *
	 * @param int    $product_id the WC product ID.
	 * @param string $sku the WC product SKU.
	 *
	 * @return void
	 */
	public static function delete_orphan_sku( $product_id, $sku ) {

		global $wpdb;

		$wpdb->delete(
			$wpdb->postmeta,
			array(
				'post_id'    => $product_id,
				'meta_key'   => '_sku',
				'meta_value' => $sku,
			)
		);

	}


	/**
	 * Search product by SKU
	 *
	 * @param string $sku the WC prodcut SKU.
	 * @param int    $parent_product_id the parent product ID.
	 *
	 * @return int
	 */
	public static function search_product( $sku, $parent_product_id = null ) {

		$post_id = null;
		$result  = wc_get_product_id_by_sku( $sku );
		$product = wc_get_product( $post_id );

		if ( $result ) {

			if ( wc_get_product( $result ) ) {

				$post_id = $result;

			} else {

				/* Delete the orphan sku */
				self::delete_orphan_sku( $result, $sku );

				$post_id = null;
			}
		} else {

			$post_id = null;

		}

		if ( ! $post_id && $parent_product_id && is_numeric( $sku ) ) {

			$product = wc_get_product( $sku );

			if ( $product && ! is_wp_error( $product ) ) {

				$post_id = intval( $parent_product_id ) === $product->get_parent_id() ? $product->get_id() : null;

			}
		}

		return $post_id;

	}


	/**
	 * Add a tax term to the given product
	 *
	 * @param int     $product_id the WC product ID.
	 * @param string  $category   the Danea cat to be added to the product.
	 * @param integer $parent_id  the parent tax term ID if exists.
	 * @param boolean $append     append to other terms with true, replace with false.
	 *
	 * @return array
	 */
	public static function add_taxonomy_term( $product_id, $category, $parent_id = 0, $append = false ) {

		$append = '1' === get_option( 'wcifd-deleting-categories' ) ? true : $append;
		$term   = term_exists( $category, 'product_cat', $parent_id );

		if ( 0 === $term || null === $term ) {
			$term = wp_insert_term( $category, 'product_cat', array( 'parent' => $parent_id ) );
		}

		if ( ! is_wp_error( $term ) ) {

            /* Get the product */
            $product = wc_get_product( $product_id );

            $categories = array();

            if ( $append ) {

                $categories = $product->get_category_ids();
            }

            $categories[] = $term['term_id'];

            $product->set_category_ids( $categories );
            $product->save();

		}

		return $term;

	}


	/**
	 * Add a new tax class in WC
	 *
	 * @param string $tax_name the tax class name.
	 *
	 * @return void
	 */
	public static function add_tax_rate_class( $tax_name ) {

		global $wpdb;

		$response = $wpdb->insert(
			$wpdb->prefix . 'wc_tax_rate_classes',
			array(
				'name' => $tax_name,
				'slug' => sanitize_title_with_dashes( $tax_name ),
			),
			array(
				'%s',
				'%s',
			)
		);

	}


	/**
	 * Get tax rate class
	 *
	 * @param  string $name  the tax rate name.
	 * @param  string $value the tax rate value.
	 *
	 * @return string
	 */
	public static function get_tax_rate_class( $name, $value = '' ) {

        $tax_rate_class = null;

		/* If a value is not passed, use the tax name if numeric */
		if ( '' === $value ) {
			$value = ( is_numeric( $name ) ) ? $name : '';
		}

		global $wpdb;

		$results = $wpdb->get_results(
			$wpdb->prepare(
				"
                SELECT * FROM {$wpdb->prefix}woocommerce_tax_rates WHERE tax_rate_name = %s
                ",
				$name
			),
			ARRAY_A
		);

		if ( $results ) {

			$tax_rate_class = ( $results[0]['tax_rate_class'] ) ? $results[0]['tax_rate_class'] : '';

		} else {

			/* Create a new tax class with the numeric value only */
			if ( '' !== $value ) {
				$tax_rate_class = 22 !== $name ? $name : '';

				if ( $tax_rate_class ) {
					$tax_classes   = explode( "\n", get_option( 'woocommerce_tax_classes' ) );
					$tax_classes[] = $tax_rate_class;
					update_option( 'woocommerce_tax_classes', implode( "\n", $tax_classes ) );
				}

				/* New tax class */
				if ( $tax_rate_class ) {
					self::add_tax_rate_class( $tax_rate_class );
				}

				$response = $wpdb->insert(
					$wpdb->prefix . 'woocommerce_tax_rates',
					array(
						'tax_rate_country'  => 'IT',
						'tax_rate'          => number_format( $value, 4 ),
						'tax_rate_name'     => $name,
						'tax_rate_priority' => 1,
						'tax_rate_shipping' => 0,
						'tax_rate_class'    => $tax_rate_class,
					),
					array(
						'%s',
						'%s',
						'%s',
						'%d',
						'%d',
						'%s',
					)
				);

			}
		}

		return $tax_rate_class;

	}

	/**
	 * Register taxonomy
	 *
	 * @param string $name the taxonomy name.
	 *
	 * @return void
	 */
	public function register_taxonomy( $name ) {

		$paname = 'pa_' . $name;

		if ( ! get_taxonomy( $paname ) ) {

			$permalinks    = get_option( 'woocommerce_permalinks' );
			$taxonomy_data = array(
				'hierarchical'          => true,
				'update_count_callback' => '_update_post_term_count',
				'labels'                => array(
					'name'              => $name,
					'singular_name'     => $name,
					/* Translators: the taxonomy name */
					'search_items'      => sprintf( __( 'Search %s', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'all_items'         => sprintf( __( 'All %s', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'parent_item'       => sprintf( __( 'Parent %s', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'parent_item_colon' => sprintf( __( 'Parent %s:', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'edit_item'         => sprintf( __( 'Edit %s', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'update_item'       => sprintf( __( 'Update %s', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'add_new_item'      => sprintf( __( 'Add New %s', 'woocommerce' ), $name ),
					/* Translators: the taxonomy name */
					'new_item_name'     => sprintf( __( 'New %s', 'woocommerce' ), $name ),
				),
				'show_ui'               => false,
				'query_var'             => true,
				'rewrite'               => array(
					'slug'         => empty( $permalinks['attribute_base'] ) ? '' : trailingslashit( $permalinks['attribute_base'] ) . sanitize_title( $name ),
					'with_front'   => false,
					'hierarchical' => true,
				),
				'sort'                  => false,
				'public'                => true,
				'show_in_nav_menus'     => false,
				'capabilities'          => array(
					'manage_terms' => 'manage_product_terms',
					'edit_terms'   => 'edit_product_terms',
					'delete_terms' => 'delete_product_terms',
					'assign_terms' => 'assign_product_terms',
				),
			);

			register_taxonomy( $paname, array( 'product' ), $taxonomy_data );

		}

	}


	/**
	 * Register attributes
	 *
	 * @return void
	 */
	public function register_attributes() {

		$attributes = array(
			'size'             => __( 'Size', 'wc-importer-for-danea' ),
			'color'            => __( 'Color', 'wc-importer-for-danea' ),
			'producer'         => __( 'Producer', 'wc-importer-for-danea' ),
			'supplier'         => __( 'Supplier', 'wc-importer-for-danea' ),
			'sup-product-code' => __( 'Supplier product code', 'wc-importer-for-danea' ),
		);

		$additional_attributes = array();

		if ( isset( $_POST['wcifd-custom-fields-hidden'], $_POST['wcifd-products-fields-nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wcifd-products-fields-nonce'] ) ), 'wcifd-products-fields' ) ) {

			/* Get the Danea free fields enabled by the admin */
			$custom_fields = get_option( 'wcifd-custom-fields' );

			if ( $custom_fields && is_array( $custom_fields ) ) {

				$count_custom_fields = count( $custom_fields );

				for ( $i = 1; $i <= $count_custom_fields; $i++ ) {

					if ( isset( $custom_fields[ $i ]['import'] ) && 'attribute' === $custom_fields[ $i ]['import'] ) {

						$custom_field_name = isset( $_POST[ 'custom-field-name-' . $i ] ) ? sanitize_text_field( wp_unslash( $_POST[ 'custom-field-name-' . $i ] ) ) : null;

						/* Translators: the custom field number */
						$name = $custom_field_name ? $custom_field_name : sprintf( __( 'Custom Field %d', 'wc-importer-for-danea' ), $i );

						$additional_attributes[ 'customfield' . $i ] = $name;

					}
				}
			}
		}

		global $wpdb;

		/* The changed attributes */
		$changes = array();

		/* Merge the attributes */
		$all_attributes = array_merge( $attributes, $additional_attributes );

		foreach ( $all_attributes as $key => $value ) {

			/* Register the taxonomy */
			$this->register_taxonomy( $key );

			$taxonomies       = wc_get_attribute_taxonomies();
			$taxonomies_names = array_values( wp_list_pluck( $taxonomies, 'attribute_name' ) );

			$results = $wpdb->get_results(
				$wpdb->prepare(
					"
                    SELECT * FROM {$wpdb->prefix}woocommerce_attribute_taxonomies WHERE attribute_name = %s
                    ",
					$key
				),
				ARRAY_A
			);

			/* Add record if not present */
			if ( ! $results ) {

				$changes[] = $key;

				$insert = $wpdb->insert(
					$wpdb->prefix . 'woocommerce_attribute_taxonomies',
					array(
						'attribute_name'    => sanitize_title( $key ),
						'attribute_label'   => $value,
						'attribute_type'    => 'select',
						'attribute_orderby' => 'menu_order',
						'attribute_public'  => 0,
					),
					array(
						'%s',
						'%s',
						'%s',
						'%s',
						'%d',
					)
				);

				/* Update record in case of name changed */
			} elseif ( isset( $results[0]['attribute_label'] ) && $results[0]['attribute_label'] !== $value ) {

				$changes[] = $key;

				$update = $wpdb->update(
					$wpdb->prefix . 'woocommerce_attribute_taxonomies',
					array(
						'attribute_label' => $value,
					),
					array(
						'attribute_name' => sanitize_title( $key ),
					),
					array(
						'%s',
					),
					array(
						'%s',
					)
				);

			}
		}

		if ( ! empty( $changes ) ) {
			$this->update_transient_wc_attributes();
		}

	}


	/**
	 * Update transient
	 *
	 * @return void
	 */
	public function update_transient_wc_attributes() {
		global $wpdb;
		$query   = '
        ';
		$results = $wpdb->get_results(
			"
            SELECT * FROM {$wpdb->prefix}woocommerce_attribute_taxonomies
            "
		);

		$data = array();
		foreach ( $results as $key => $value ) {
			$data[ $key ] = $value;
		}

		update_option( '_transient_wc_attribute_taxonomies', $data );
	}


	/**
	 * Get the gross or net price from the Danea XML based on the admin set
	 *
	 * @param array   $d_product    the product received from Danea Easyfatt. 
	 * @param int     $number       the price list set.
	 * @param boolean $tax_included gross price with true.
	 *
	 * @return stringa the price
	 */
	public static function get_list_price( $d_product, $number, $tax_included = false ) {

        $output = null;

		$gross_price = 'GrossPrice' . $number;
		$net_price   = 'NetPrice' . $number;

		if ( $tax_included ) {
			$output = isset( $d_product[ $gross_price ] ) ? $d_product[ $gross_price ] : '';
		} else {
			$output = isset( $d_product[ $net_price ] ) ? $d_product[ $net_price ] : '';
		}

		return $output;

	}


	/**
	 * Get prices with labels for every user roles set with WC Role Based Price
	 *
	 * @return array
	 */
	public static function get_wc_rbp() {

		$output         = null;
		$wc_rbp_general = get_option( 'wc_rbp_general' );

		if ( function_exists( 'woocommerce_role_based_price' ) && $wc_rbp_general ) {
			$wc_rbp_allowed_roles = isset( $wc_rbp_general['wc_rbp_allowed_roles'] ) ? $wc_rbp_general['wc_rbp_allowed_roles'] : '';
			$wc_rbp_allowed_price = isset( $wc_rbp_general['wc_rbp_allowed_price'] ) ? $wc_rbp_general['wc_rbp_allowed_price'] : '';

			if ( $wc_rbp_allowed_roles ) {
				$output = array();
				foreach ( $wc_rbp_allowed_roles as $role ) {
					foreach ( $wc_rbp_allowed_price as $price_type ) {
						$field_name = $price_type . '_' . $role;
						$price_list = get_option( 'wcifd_' . $field_name );

						$output[ $role ][ $price_type ] = $price_list;

					}
				}
			}
		}

		return $output;
	}


	/**
	 * Get the product size
	 *
	 * @param  array   $product the product.
	 * @param  string  $type    gross or net measures.
	 * @param  string  $measure the param to be returned.
	 * @param  boolean $csv     csv with true, object instead.
	 *
	 * @return string
	 */
	public static function get_product_size( $product, $type, $measure, $csv = false ) {

		$x = null;
		$y = null;
		$z = null;
		if ( 'gross-size' === $type ) {
			if ( $csv ) {
				$x = isset( $product['Dim. imballo X'] ) ? $product['Dim. imballo X'] : '';
				$y = isset( $product['Dim. imballo Y'] ) ? $product['Dim. imballo Y'] : '';
				$z = isset( $product['Dim. imballo Z'] ) ? $product['Dim. imballo Z'] : '';
			} else {
				$x = isset( $product['PackingSizeX'] ) ? $product['PackingSizeX'] : '';
				$y = isset( $product['PackingSizeY'] ) ? $product['PackingSizeY'] : '';
				$z = isset( $product['PackingSizeZ'] ) ? $product['PackingSizeZ'] : '';
			}
		} else {
			if ( $csv ) {
				$x = isset( $product['Dim. netta X'] ) ? $product['Dim. netta X'] : '';
				$y = isset( $product['Dim. netta Y'] ) ? $product['Dim. netta Y'] : '';
				$z = isset( $product['Dim. netta Z'] ) ? $product['Dim. netta Z'] : '';
			} else {
				$x = isset( $product['NetSizeX'] ) ? $product['NetSizeX'] : '';
				$y = isset( $product['NetSizeY'] ) ? $product['NetSizeY'] : '';
				$z = isset( $product['NetSizeZ'] ) ? $product['NetSizeZ'] : '';
			}
		}

		switch ( $measure ) {
			case 'x':
				$output = $x;
				break;

			case 'y':
				$output = $y;
				break;

			case 'z':
				$output = $z;
				break;
		}

		return $output;

	}


	/**
	 * Generate a short description of the product
	 *
	 * @param  string $description the full description of the product.
	 *
	 * @return string
	 */
	public static function get_short_description( $description ) {
		$output = null;

		$description = wp_strip_all_tags( $description );

		if ( strlen( $description ) > 340 ) {
			$output = substr( $description, 0, 340 ) . '...';
		} else {
			$output = $description;
		}

		return $output;
	}


	/**
	 * Receive the HTTP POST call from Danea Easyfatt
	 *
	 * @return void
	 */
	public function products_update_request() {

		$premium_key   = strtolower( get_option( 'wcifd-premium-key' ) );
		$url_code      = strtolower( get_option( 'wcifd-url-code' ) );
		$import_images = get_option( 'wcifd-import-images' );
		$key           = isset( $_GET['key'] ) ? sanitize_text_field( wp_unslash( $_GET['key'] ) ) : '';
		$code          = isset( $_GET['code'] ) ? sanitize_text_field( wp_unslash( $_GET['code'] ) ) : '';
		$mode          = isset( $_GET['mode'] ) ? sanitize_text_field( wp_unslash( $_GET['mode'] ) ) : '';

		if ( $key && $code ) {

			if ( $key === $premium_key && $code === $url_code ) {

				$images_send_url        = sprintf( '%1$s?key=%2$s&code=%3$s&mode=images', home_url(), $key, $code );
				$images_send_finish_url = sprintf( '%s-send-finish', $images_send_url );

				/* Products import */
				if ( 'data' === $mode ) {

					if ( isset( $_FILES['file']['tmp_name'] ) && move_uploaded_file( sanitize_text_field( wp_unslash( $_FILES['file']['tmp_name'] ) ), 'wcifd-prodotti.xml' ) ) {

						new WCIFD_Catalog_Update( 'wcifd-prodotti.xml' );

						echo "OK\n";

						if ( 1 === intval( $import_images ) ) {

							printf( "ImageSendURL=%s\n", esc_url_raw( $images_send_url ) );
							printf( "ImageSendFinishURL=%s\n", esc_url_raw( $images_send_finish_url ) );

						}
					} else {

						esc_html_e( 'WCIFD ERROR | An error accourred while receiving data from Danea Easyfatt', 'wc-importer-for-danea' );

					}
				} elseif ( 'images' === $mode && 1 === intval( $import_images ) ) {

					/* Images update */
					wcifd_products_images();

				} elseif ( 'images-send-finish' === $mode && 1 === intval( $import_images ) ) {

					echo "OK\n";

					/* Orphan images management */
					$next = as_next_scheduled_action(
						'wcifd_orphan_images_event',
						array(),
						'wcifd-orphan-images'
					);

					if ( ! $next ) {

						as_schedule_recurring_action(
							time(),
							60,
							'wcifd_orphan_images_event',
							array(),
							'wcifd-orphan-images'
						);

					}
				}
			} else {

				echo wp_kses_post( __( 'WCIFD ERROR | It seems like the URL entered in Danea Easyfatt is not correct', 'wc-importer-for-danea' ) );

			}

			exit;

		}

	}


	/**
	 * Custom check for update message
	 *
	 * @return string
	 */
	public function check_update_message() {

		return __( 'Check for updates', 'wc-importer-for-danea' );

	}


	/**
	 * Custom update message
	 *
	 * @param  string $message the message text.
	 * @param  string $status the answer status.
	 *
	 * @return string
	 */
	public function update_message( $message = '', $status = '' ) {

		if ( 'no_update' === $status ) {

			$message = __( '<strong>Woocommerce Importer for Danea - Premium</strong> is up to date.', 'wc-importer-for-danea' );

		} elseif ( 'update_available' === $status ) {

			$message = __( 'A new version of <strong>Woocommerce Importer for Danea - Premium</strong> is available.', 'wc-importer-for-danea' );

		} else {

			$message = __( 'There was an error trying to update. Please try again later.', 'wc-importer-for-danea' );

		}

		return $message;

	}

}

new WCIFD_Functions();

